"""Fallback city -> country lookup for the common case where a job API
gives a bare city name with no country (e.g. "Berlin", "London") — very
common on European boards like Arbeitnow. Covers major tech hubs only;
anything not listed here still safely falls back to (None, None, None)
in location.py rather than a wrong guess."""

CITY_TO_COUNTRY = {
    "berlin": "Germany", "munich": "Germany", "hamburg": "Germany", "cologne": "Germany",
    "köln": "Germany", "frankfurt": "Germany", "stuttgart": "Germany", "düsseldorf": "Germany",
    "dusseldorf": "Germany", "darmstadt": "Germany", "heidelberg": "Germany", "mannheim": "Germany",
    "leipzig": "Germany", "dresden": "Germany", "nuremberg": "Germany",
    "london": "United Kingdom", "manchester": "United Kingdom", "birmingham": "United Kingdom",
    "glasgow": "United Kingdom", "edinburgh": "United Kingdom", "bristol": "United Kingdom",
    "leeds": "United Kingdom", "liverpool": "United Kingdom", "cambridge": "United Kingdom",
    "oxford": "United Kingdom",
    "paris": "France", "lyon": "France", "marseille": "France", "toulouse": "France",
    "nice": "France", "bordeaux": "France", "gardanne": "France",
    "madrid": "Spain", "barcelona": "Spain", "valencia": "Spain", "seville": "Spain",
    "rome": "Italy", "milan": "Italy", "turin": "Italy", "naples": "Italy",
    "amsterdam": "Netherlands", "rotterdam": "Netherlands", "utrecht": "Netherlands",
    "the hague": "Netherlands", "eindhoven": "Netherlands",
    "brussels": "Belgium", "antwerp": "Belgium",
    "zurich": "Switzerland", "geneva": "Switzerland", "basel": "Switzerland", "bern": "Switzerland",
    "vienna": "Austria", "graz": "Austria",
    "stockholm": "Sweden", "gothenburg": "Sweden", "malmo": "Sweden", "malmö": "Sweden",
    "copenhagen": "Denmark", "aarhus": "Denmark",
    "oslo": "Norway", "bergen": "Norway",
    "helsinki": "Finland", "espoo": "Finland",
    "warsaw": "Poland", "krakow": "Poland", "wroclaw": "Poland",
    "prague": "Czechia", "brno": "Czechia",
    "budapest": "Hungary",
    "lisbon": "Portugal", "porto": "Portugal",
    "athens": "Greece", "thessaloniki": "Greece",
    "dublin": "Ireland", "cork": "Ireland",
    "bucharest": "Romania", "cluj-napoca": "Romania",
    "sofia": "Bulgaria",
    "zagreb": "Croatia",
    "tallinn": "Estonia", "riga": "Latvia", "vilnius": "Lithuania",
    "kyiv": "Ukraine", "kiev": "Ukraine",
    "moscow": "Russia", "saint petersburg": "Russia",
    "istanbul": "Turkey", "ankara": "Turkey",
    "new york": "United States", "san francisco": "United States", "los angeles": "United States",
    "chicago": "United States", "boston": "United States", "seattle": "United States",
    "austin": "United States", "denver": "United States", "miami": "United States",
    "atlanta": "United States", "dallas": "United States", "houston": "United States",
    "washington": "United States", "washington dc": "United States", "philadelphia": "United States",
    "san diego": "United States", "portland": "United States", "phoenix": "United States",
    "san jose": "United States", "nashville": "United States", "detroit": "United States",
    "toronto": "Canada", "vancouver": "Canada", "montreal": "Canada", "ottawa": "Canada",
    "calgary": "Canada",
    "mexico city": "Mexico", "guadalajara": "Mexico",
    "sao paulo": "Brazil", "são paulo": "Brazil", "rio de janeiro": "Brazil",
    "buenos aires": "Argentina",
    "bogota": "Colombia", "bogotá": "Colombia",
    "santiago": "Chile",
    "lima": "Peru",
    "tokyo": "Japan", "osaka": "Japan", "yokohama": "Japan",
    "seoul": "South Korea", "busan": "South Korea",
    "beijing": "China", "shanghai": "China", "shenzhen": "China", "guangzhou": "China",
    "hong kong": "China", "taipei": "Taiwan",
    "singapore": "Singapore",
    "mumbai": "India", "bangalore": "India", "bengaluru": "India", "delhi": "India",
    "new delhi": "India", "hyderabad": "India", "pune": "India", "chennai": "India",
    "gurgaon": "India", "gurugram": "India", "noida": "India",
    "jakarta": "Indonesia",
    "manila": "Philippines",
    "bangkok": "Thailand",
    "ho chi minh city": "Vietnam", "hanoi": "Vietnam",
    "kuala lumpur": "Malaysia",
    "sydney": "Australia", "melbourne": "Australia", "brisbane": "Australia", "perth": "Australia",
    "auckland": "New Zealand", "wellington": "New Zealand",
    "tel aviv": "Israel", "jerusalem": "Israel",
    "dubai": "United Arab Emirates", "abu dhabi": "United Arab Emirates",
    "riyadh": "Saudi Arabia", "jeddah": "Saudi Arabia",
    "cairo": "Egypt",
    "lagos": "Nigeria", "nairobi": "Kenya", "cape town": "South Africa",
    "johannesburg": "South Africa",
}

COUNTRY_CODE_ALIASES = {
    "de": "Germany", "fr": "France", "uk": "United Kingdom", "gb": "United Kingdom",
    "us": "United States", "usa": "United States", "es": "Spain", "it": "Italy",
    "nl": "Netherlands", "be": "Belgium", "ch": "Switzerland", "at": "Austria",
    "se": "Sweden", "dk": "Denmark", "no": "Norway", "fi": "Finland", "pl": "Poland",
    "cz": "Czechia", "pt": "Portugal", "ie": "Ireland", "ca": "Canada", "au": "Australia",
    "in": "India", "sg": "Singapore", "jp": "Japan", "deutschland": "Germany",
}


def lookup_city_country(city: str) -> str | None:
    return CITY_TO_COUNTRY.get(city.strip().lower())
